# MyABCs Makefile for BSD systems.
# Created by Jordan Irwin.

.include "make_definitions"

.if defined(DEBUG)
CFLAGS=-c -Wall -g -I${DIR_INCL}
CXXFLAGS=${CFLAGS}
LDFLAGS=${SDLLIBS}
.endif

.if defined(WIN32) || defined(__WIN32__)
LIBS=-lmingw -lSDLmain -lSDL
EXE_SUF=.exe
EXE=${PNAME}${EXE_SUF}
.endif

.include "make_directives"
