#ifndef MYABCS_RES_H
#define MYABCS_RES_H

#if !defined(WIN32) && !defined(WIN64)
#define ICON1 _T("myabcs.png")
#else
#define ID_ICON1
#define ICON1 wxICON(ID_ICON1)
#endif

#define RIBBON _T("data/image/ribbon.png")
#define HELP "data/image/help.png"
#define INFO "data/image/info.png"

#define DATAPATH "data"
#define IMGPATH "data/image"
#define IMG_MAIN "data/image/main"

#define ICO_ABC "data/image/abc.png"
#define ICO_EXIT "data/image/exit.png"
#define ICO_FOOD "data/image/food.png"
#define ICO_INSTR "data/image/instrument.png"
#define ICO_TOY "data/image/toy.png"
#define ICO_ANIMAL "data/image/animal.png"

// Main
#define AIRPLANE _T("data/image/main/airplane.png")
#define BICYCLE _T("data/image/main/bicycle.png")
#define CLOCK _T("data/image/main/clock.png")
#define DOLPHIN _T("data/image/main/dolphin.png")
#define EARTH _T("data/image/main/earth.png")
#define FIRE _T("data/image/main/fire.png")
#define GRASSHOPPER _T("data/image/main/grasshopper.png")
#define HAT _T("data/image/main/hat.png")
#define IGLOO _T("data/image/main/igloo.png")
#define JAR _T("data/image/main/jar.png")
#define KEYBOARD _T("data/image/main/keyboard.png")
#define LADYBUG _T("data/image/main/ladybug.png")
#define MAG_GLASS _T("data/image/main/mag_glass.png")
#define NEWS _T("data/image/main/newspaper.png")
#define ONION _T("data/image/main/onion.png")
#define PAPER_PLANE _T("data/image/main/paper_airplane.png")
#define QUARTER _T("data/image/main/quarter.png")
#define RACCOON _T("data/image/main/raccoon.png")
#define STAR _T("data/image/main/star.png")
#define TRAIN _T("data/image/main/train.png")
#define UMBRELLA _T("data/image/main/umbrella.png")
#define VASE _T("data/image/main/vase.png")
#define WATCH _T("data/image/main/watch.png")
#define X_RAY _T("data/image/main/x_ray.png")
#define YINYANG _T("data/image/main/yinyang.png")
#define ZIPPER _T("data/image/main/zipper.png")

// Foods
#define APPLE _T("data/image/food/apple.png")
#define BANANAS _T("data/image/food/bananas.png")
#define CHERRIES _T("data/image/food/cherries.png")
#define DOUGHNUT _T("data/image/food/doughnut.png")
#define EGG _T("data/image/food/egg.png")
#define FRIES _T("data/image/food/fries.png")
#define GRAPES _T("data/image/food/grapes.png")
#define HOT_DOG _T("data/image/food/hot_dog.png")
#define ICE_CREAM _T("data/image/food/ice_cream.png")
#define JUICE _T("data/image/food/juice.png")
#define KETCHUP _T("data/image/food/ketchup.png")
#define LASAGNA _T("data/image/food/lasagna.png")
#define MUSHROOM _T("data/image/food/mushroom.png")
#define NOODLE _T("data/image/food/noodle.png")
#define OLIVE _T("data/image/food/olive.png")
#define PIE _T("data/image/food/pie.png")
#define PRETZEL _T("data/image/food/pretzel.png")
#define QUICHE _T("data/image/food/quiche.png")
#define RADISHES _T("data/image/food/radishes.png")
#define STRAWBERRY _T("data/image/food/strawberry.png")
#define TOMATO _T("data/image/food/tomato.png")
#define UDON _T("data/image/food/udon.png")
#define VEGETABLES _T("data/image/food/vegetables.png")
#define WATERMELON _T("data/image/food/watermelon.png")
#define XCOOKIE _T("data/image/food/x_cookie.png")
#define YAM _T("data/image/food/yam.png")
#define ZUCCHINI _T("data/image/food/zucchini.png")

// Animals
#define AARDVARK _T("data/image/animal/aardvark.png")
#define ALLIGATOR _T("data/image/animal/alligator.png")
#define ANGELFISH _T("data/image/animal/angelfish.png")
#define ANT _T("data/image/animal/ant.png")
#define ANGELFISH _T("data/image/animal/angelfish.png")
#define ARMADILLO _T("data/image/animal/armadillo.png")
#define BUTTERFLY _T("data/image/animal/butterfly.png")
#define BIRD _T("data/image/animal/bird.png")
#define CAT _T("data/image/animal/cat.png")
#define DOG _T("data/image/animal/dog.png")
#define ELEPHANT _T("data/image/animal/elephant.png")
#define FROG _T("data/image/animal/frog.png")
#define GIRAFFE _T("data/image/animal/giraffe.png")
#define HIPPO _T("data/image/animal/hippo.png")
#define HORSE _T("data/image/animal/horse.png")
#define IBIS _T("data/image/animal/ibis.png")
#define IGUANA _T("data/image/animal/iguana.png")
#define JAGUAR _T("data/image/animal/jaguar.png")
#define KOALA _T("data/image/animal/koala.png")
#define LION _T("data/image/animal/lion.png")
#define MOUSE _T("data/image/animal/mouse.png")
#define NEWT _T("data/image/animal/newt.png")
#define NIGHTINGALE _T("data/image/animal/nightingale.png")
#define ORCA _T("data/image/animal/orga.png")
#define OWL _T("data/image/animal/owl.png")
#define PIG _T("data/image/animal/pig.png")
#define QUAIL _T("data/image/animal/quail.png")
#define ROOSTER _T("data/image/animal/rooster.png")
#define SHEEP _T("data/image/animal/sheep.png")
#define TURTLE _T("data/image/animal/turtle.png")
#define UNICORN _T("data/image/animal/unicorn.png")
#define URCHIN _T("data/image/animal/urchin.png")
#define VULTURE _T("data/image/animal/vulture.png")
#define WEASEL _T("data/image/animal/weasel.png")
#define WHALE _T("data/image/animal/whale.png")
#define XIPHIAS _T("data/image/animal/xiphias.png")
#define YAK _T("data/image/animal/yak.png")
#define ZEBRA _T("data/image/animal/zebra.png")

// Music
#define ACCORDION _T("data/image/music/accordion.png")
#define BAGPIPES _T("data/image/music/bagpipes.png")
#define CLARINET _T("data/image/music/clarinet.png")
#define DRUMS _T("data/image/music/drums.png")
#define EGUITAR _T("data/image/music/electric_guitar.png")
#define EUPHONIUM _T("data/image/music/euphonium.png")
#define FLUTE _T("data/image/music/flute.png") // Creative Commons
#define GUITAR _T("data/image/music/guitar.png")
#define HARP _T("data/image/music/harp.png")
#define IPU _T("data/image/music/ipu.png")
#define JUG _T("data/image/music/jug.png")
#define KAZOO _T("data/image/music/kazoo.png")
#define LUTE _T("data/image/music/lute.png")
#define MARACAS _T("data/image/music/maracas.png")
#define NEY _T("data/image/music/ney.png")
#define OBOE _T("data/image/music/oboe.png")
#define PIANO _T("data/image/music/piano.png")
#define QUENA _T("data/image/music/quena.png")
#define RECORDER _T("data/image/music/recorder.png")
#define SAX _T("data/image/music/sax.png")
#define TRUMPET _T("data/image/music/trumpet.png")
#define UKULELE _T("data/image/music/ukulele.png")
#define VIOLIN _T("data/image/music/violin.png")
#define WHISTLE _T("data/image/music/whistle.png")
#define XUN _T("data/image/music/xun.png")
#define YANGQIN _T("data/image/music/yangqin.png") // ???
#define ZURNA _T("data/image/music/zurna.png")

// Toys
#define ANKLET _T("data/image/toy/anklet.png")
#define BALLOONS _T("data/image/toy/balloons.png")
#define CHALKBOARD _T("data/image/toy/chalkboard.png")
#define DOLL _T("data/image/toy/doll.png")
#define EASEL _T("data/image/toy/easel.png")
#define FOOTBALL _T("data/image/toy/football.png")
#define GLOVE _T("data/image/toy/glove.png")
#define HORN _T("data/image/toy/horn.png")
#define ICE_SKATE _T("data/image/toy/ice_skate.png")
#define JUMP_ROPE _T("data/image/toy/jump_rope.png")
#define KITE _T("data/image/toy/kite.png")
#define LUNCHBOX _T("data/image/toy/lunchbox.png")
#define MAGNET _T("data/image/toy/magnet.png")
#define NECKLACE _T("data/image/toy/necklace.png")
#define ORIGAMI _T("data/image/toy/origami.png")
#define PAINT _T("data/image/toy/paint.png")
#define QUILT _T("data/image/toy/quilt.png")
#define ROCK_HORSE _T("data/image/toy/rocking_horse.png")
#define SEESAW _T("data/image/toy/seesaw.png")
#define TOP _T("data/image/toy/top.png")
#define UNICYCLE _T("data/image/toy/unicycle.png") // GNU Free Documentation License
#define VOLLEYBALL _T("data/image/toy/volleyball.png")
#define WAGON _T("data/image/toy/wagon.png")
#define XYLOPHONE _T("data/image/toy/xylophone.png")
#define YOYO _T("data/image/toy/yoyo.png")
#define ZIPLINE _T("data/image/toy/zipline.png")

// Sounds
#define CHEER _T("sound/cheering.wav")

#define A _T("sound/alpha/A.wav")
#define B _T("sound/alpha/B.wav")
#define C _T("sound/alpha/C.wav")
#define D _T("sound/alpha/D.wav")
#define E _T("sound/alpha/E.wav")
#define F _T("sound/alpha/F.wav")
#define G _T("sound/alpha/G.wav")
#define H _T("sound/alpha/H.wav")
#define I _T("sound/alpha/I.wav")
#define J _T("sound/alpha/J.wav")
#define K _T("sound/alpha/K.wav")
#define L _T("sound/alpha/L.wav")
#define M _T("sound/alpha/M.wav")
#define N _T("sound/alpha/N.wav")
#define O _T("sound/alpha/O.wav")
#define P _T("sound/alpha/P.wav")
#define Q _T("sound/alpha/Q.wav")
#define R _T("sound/alpha/R.wav")
#define S _T("sound/alpha/S.wav")
#define T _T("sound/alpha/T.wav")
#define U _T("sound/alpha/U.wav")
#define V _T("sound/alpha/V.wav")
#define W _T("sound/alpha/W.wav")
#define X _T("sound/alpha/X.wav")
#define Y _T("sound/alpha/Y.wav")
#define Z _T("sound/alpha/Z.wav")


#endif /* MYABCS_RES_H */
