#ifndef MYABCS_RES_H
#define MYABCS_RES_H

#if !defined(WIN32) && !defined(WIN64)
#define ICON1 _T("myabcs.png")
#else
#define ID_ICON1
#define ICON1 wxICON(ID_ICON1)
#endif

#define RIBBON _T("pic/ribbon")
#define QUESTION _T("pic/question")

// Foods
#define APPLE _T("pic/food/apple")
#define BANANAS _T("pic/food/bananas")
#define CHERRIES _T("pic/food/cherries")
#define DOUGHNUT _T("pic/food/doughnut")
#define EGG _T("pic/food/egg")
#define FRIES _T("pic/food/fries")
#define GRAPES _T("pic/food/grapes")
#define HOT_DOG _T("pic/food/hot_dog")
#define ICE_CREAM _T("pic/food/ice_cream")
#define JUICE _T("pic/food/juice")
#define KETCHUP _T("pic/food/ketchup")
#define LASAGNA _T("pic/food/lasagna")
#define MUSHROOM _T("pic/food/mushroom")
#define NOODLE _T("pic/food/noodle")
#define OLIVE _T("pic/food/olive")
#define ONION _T("pic/food/onion")
#define PIE _T("pic/food/pie")
#define PRETZEL _T("pic/food/pretzel")
#define QUICHE _T("pic/food/quiche")
#define RADISHES _T("pic/food/radishes")
#define STRAWBERRY _T("pic/food/strawberry")
#define TOMATO _T("pic/food/tomato")
#define UDON _T("pic/food/udon")
#define VEGETABLES _T("pic/food/vegetables")
#define WATERMELON _T("pic/food/watermelon")
#define XCOOKIE _T("pic/food/x_cookie")
#define YAM _T("pic/food/yam")
#define ZUCCHINI _T("pic/food/zucchini")

// Animals
#define AARDVARK _T("pic/animals/aardvark")
#define ALLIGATOR _T("pic/animals/alligator")
#define ANGELFISH _T("pic/animals/angelfish")
#define ANT _T("pic/animals/ant")
#define ANGELFISH _T("pic/animals/angelfish")
#define ARMADILLO _T("pic/animals/armadillo")
#define BUTTERFLY _T("pic/animals/butterfly")
#define BIRD _T("pic/animals/bird")
#define CAT _T("pic/animals/cat")
#define DOG _T("pic/animals/dog")
#define DOLPHIN _T("pic/animals/dolphin")
#define ELEPHANT _T("pic/animals/elephant")
#define FROG _T("pic/animals/frog")
#define GIRAFFE _T("pic/animals/giraffe")
#define GRASSHOPPER _T("pic/animals/grasshopper")
#define HIPPO _T("pic/animals/hippo")
#define HORSE _T("pic/animals/horse")
#define IBIS _T("pic/animals/ibis")
#define IGUANA _T("pic/animals/iguana")
#define JAGUAR _T("pic/animals/jaguar")
#define KOALA _T("pic/animals/koala")
#define LADYBUG _T("pic/animals/ladybug")
#define LION _T("pic/animals/lion")
#define MOUSE _T("pic/animals/mouse")
#define NEWT _T("pic/animals/newt")
#define NIGHTINGALE _T("pic/animals/nightingale")
#define ORCA _T("pic/animals/orca") // UNUSED
#define OWL _T("pic/animals/owl")
#define PIG _T("pic/animals/pig")
#define QUAIL _T("pic/animals/quail")
#define RACCOON _T("pic/animals/raccoon")
#define ROOSTER _T("pic/animals/rooster")
#define SHEEP _T("pic/animals/sheep")
#define TURTLE _T("pic/animals/turtle")
#define UNICORN _T("pic/animals/unicorn")
#define URCHIN _T("pic/animals/urchin")
#define VULTURE _T("pic/animals/vulture")
#define WEASEL _T("pic/animals/weasel")
#define WHALE _T("pic/animals/whale")
#define XIPHIAS _T("pic/animals/xiphias")
#define YAK _T("pic/animals/yak")
#define ZEBRA _T("pic/animals/zebra")

// Music
#define ACCORDION _T("pic/music/accordion")
#define BAGPIPES _T("pic/music/bagpipes")
#define CLARINET _T("pic/music/clarinet")
#define DRUMS _T("pic/music/drums")
#define EGUITAR _T("pic/music/electric_guitar")
#define EUPHONIUM _T("pic/music/euphonium")
#define FLUTE _T("pic/music/flute") // Creative Commons
#define GUITAR _T("pic/music/guitar")
#define HARP _T("pic/music/harp")
#define IPU _T("pic/music/ipu")
#define JUG _T("pic/music/jug")
#define KAZOO _T("pic/music/kazoo")
#define LUTE _T("pic/music/lute")
#define MARACAS _T("pic/music/maracas")
#define NEY _T("pic/music/ney")
#define OBOE _T("pic/music/oboe")
#define PIANO _T("pic/music/piano")
#define QUENA _T("pic/music/quena")
#define RECORDER _T("pic/music/recorder")
#define SAX _T("pic/music/sax")
#define TRUMPET _T("pic/music/trumpet")
#define UKULELE _T("pic/music/ukulele")
#define VIOLIN _T("pic/music/violin")
#define WHISTLE _T("pic/music/whistle")
#define XUN _T("pic/music/xun")
#define YANGQIN _T("pic/music/yangqin") // CC BY-SA
#define ZURNA _T("pic/music/zurna")

// Toys
#define ANKLET _T("pic/toys/anklet")
#define BALLOONS _T("pic/toys/balloons")
#define BICYCLE _T("pic/toys/bicycle")
#define CHALKBOARD _T("pic/toys/chalkboard")
#define DOLL _T("pic/toys/doll")
#define EASEL _T("pic/toys/easel")
#define FOOTBALL _T("pic/toys/football")
#define GLOVE _T("pic/toys/glove")
#define HORN _T("pic/toys/horn")
#define ICE_SKATE _T("pic/toys/ice_skate")
#define JUMP_ROPE _T("pic/toys/jump_rope")
#define KITE _T("pic/toys/kite")
#define LUNCHBOX _T("pic/toys/lunchbox")
#define MAGNET _T("pic/toys/magnet")
#define NECKLACE _T("pic/toys/necklace")
#define ORIGAMI _T("pic/toys/origami")
#define PAINT _T("pic/toys/paint")
#define PAPER_PLANE _T("pic/toys/paper_airplane")
#define QUILT _T("pic/toys/quilt")
#define ROCK_HORSE _T("pic/toys/rocking_horse")
#define SEESAW _T("pic/toys/seesaw")
#define TOP _T("pic/toys/top")
#define UNICYCLE _T("pic/toys/unicycle") // GNU Free Documentation License
#define VOLLEYBALL _T("pic/toys/volleyball")
#define WAGON _T("pic/toys/wagon")
#define XYLOPHONE _T("pic/toys/xylophone")
#define YOYO _T("pic/toys/yoyo")
#define ZIPLINE _T("pic/toys/zipline")

// Misc
#define AIRPLANE _T("pic/misc/airplane")
#define CLOCK _T("pic/misc/clock")
#define EARTH _T("pic/misc/earth")
#define FIRE _T("pic/misc/fire")
#define HAT _T("pic/misc/hat")
#define IGLOO _T("pic/misc/igloo")
#define JAR _T("pic/misc/jar")
#define KEYBOARD _T("pic/misc/keyboard")
#define NEWS _T("pic/misc/newspaper")
#define UMBRELLA _T("pic/misc/umbrella")
#define MAG_GLASS _T("pic/misc/mag_glass")
#define QUARTER _T("pic/misc/quarter")
#define STAR _T("pic/misc/star")
#define TRAIN _T("pic/misc/train")
#define VASE _T("pic/misc/vase")
#define WATCH _T("pic/misc/watch")
#define X_RAY _T("pic/misc/x_ray")
#define YINYANG _T("pic/misc/yinyang")
#define ZIPPER _T("pic/misc/zipper")

// Sounds
#define CHEER _T("sound/cheering.wav")

#define A _T("sound/alpha/A.wav")
#define B _T("sound/alpha/B.wav")
#define C _T("sound/alpha/C.wav")
#define D _T("sound/alpha/D.wav")
#define E _T("sound/alpha/E.wav")
#define F _T("sound/alpha/F.wav")
#define G _T("sound/alpha/G.wav")
#define H _T("sound/alpha/H.wav")
#define I _T("sound/alpha/I.wav")
#define J _T("sound/alpha/J.wav")
#define K _T("sound/alpha/K.wav")
#define L _T("sound/alpha/L.wav")
#define M _T("sound/alpha/M.wav")
#define N _T("sound/alpha/N.wav")
#define O _T("sound/alpha/O.wav")
#define P _T("sound/alpha/P.wav")
#define Q _T("sound/alpha/Q.wav")
#define R _T("sound/alpha/R.wav")
#define S _T("sound/alpha/S.wav")
#define T _T("sound/alpha/T.wav")
#define U _T("sound/alpha/U.wav")
#define V _T("sound/alpha/V.wav")
#define W _T("sound/alpha/W.wav")
#define X _T("sound/alpha/X.wav")
#define Y _T("sound/alpha/Y.wav")
#define Z _T("sound/alpha/Z.wav")


#endif /* MYABCS_RES_H */
