#if defined linux
    //#define ICON1 _T("/usr/share/pixmaps/MyABCs.xpm")
    #define ICON1 *exedir + _T("icon.xpm")
#elif defined WIN32
    #define ID_ICON1
    #define ICON1 wxICON(ID_ICON1)

#endif

#define RIBBON _T("pic/ribbon.png")
#define QUESTION _T("pic/question.png")

// Foods
#define APPLE _T("pic/food/apple.png")
#define BANANAS _T("pic/food/bananas.png")
#define CHERRIES _T("pic/food/cherries.png")
#define DOUGHNUT _T("pic/food/doughnut.png")
#define EGG _T("pic/food/egg.png")
#define FRIES _T("pic/food/fries.png")
#define GRAPES _T("pic/food/grapes.png")
#define HOT_DOG _T("pic/food/hot_dog.png")
#define ICE_CREAM _T("pic/food/ice_cream.png")
#define JUICE _T("pic/food/juice.png")
#define KETCHUP _T("pic/food/ketchup.png")
#define LASAGNA _T("pic/food/lasagna.png")
#define MUSHROOM _T("pic/food/mushroom.png")
#define NOODLE _T("pic/food/noodle.png")
#define OLIVE _T("pic/food/olive.png")
#define ONION _T("pic/food/onion.png")
#define PIE _T("pic/food/pie.png")
#define PRETZEL _T("pic/food/pretzel.png")
#define QUICHE _T("pic/food/quiche.png")
#define RADISHES _T("pic/food/radishes.png")
#define STRAWBERRY _T("pic/food/strawberry.png")
#define TOMATO _T("pic/food/tomato.png")
#define UDON _T("pic/food/udon.png")
#define VEGETABLES _T("pic/food/vegetables.png")
#define WATERMELON _T("pic/food/watermelon.png")
#define XCOOKIE _T("pic/food/x_cookie.png")
#define YAM _T("pic/food/yam.png")
#define ZUCCHINI _T("pic/food/zucchini.png")

// Animals
#define AARDVARK _T("pic/animals/aardvark.png")
#define ALLIGATOR _T("pic/animals/alligator.png")
#define ANGELFISH _T("pic/animals/angelfish.png")
#define ANT _T("pic/animals/ant.png")
#define ANGELFISH _T("pic/animals/angelfish.png")
#define ARMADILLO _T("pic/animals/armadillo.png")
#define BUTTERFLY _T("pic/animals/butterfly.png")
#define BIRD _T("pic/animals/bird.png")
#define CAT _T("pic/animals/cat.png")
#define DOG _T("pic/animals/dog.png")
#define DOLPHIN _T("pic/animals/dolphin.png")
#define ELEPHANT _T("pic/animals/elephant.png")
#define FROG _T("pic/animals/frog.png")
#define GIRAFFE _T("pic/animals/giraffe.png")
#define GRASSHOPPER _T("pic/animals/grasshopper.png")
#define HIPPO _T("pic/animals/hippo.png")
#define HORSE _T("pic/animals/horse.png")
#define IBIS _T("pic/animals/ibis.png")
#define IGUANA _T("pic/animals/iguana.png")
#define JAGUAR _T("pic/animals/jaguar.png")
#define KOALA _T("pic/animals/koala.png")
#define LADYBUG _T("pic/animals/ladybug.png")
#define LION _T("pic/animals/lion.png")
#define MOUSE _T("pic/animals/mouse.png")
#define NEWT _T("pic/animals/newt.png")
#define NIGHTINGALE _T("pic/animals/nightingale.png")
#define ORCA _T("pic/animals/orga.png")
#define OWL _T("pic/animals/owl.png")
#define PIG _T("pic/animals/pig.png")
#define QUAIL _T("pic/animals/quail.png")
#define RACCOON _T("pic/animals/raccoon.png")
#define ROOSTER _T("pic/animals/rooster.png")
#define SHEEP _T("pic/animals/sheep.png")
#define TURTLE _T("pic/animals/turtle.png")
#define UNICORN _T("pic/animals/unicorn.png")
#define URCHIN _T("pic/animals/urchin.png")
#define VULTURE _T("pic/animals/vulture.png")
#define WEASEL _T("pic/animals/weasel.png")
#define WHALE _T("pic/animals/whale.png")
#define XIPHIAS _T("pic/animals/xiphias.png")
#define YAK _T("pic/animals/yak.png") // Copyleft
#define ZEBRA _T("pic/animals/zebra.png")

// Music
#define ACCORDION _T("pic/music/accordion.png")
#define BAGPIPES _T("pic/music/bagpipes.png")
#define CLARINET _T("pic/music/clarinet.png")
#define DRUMS _T("pic/music/drums.png")
#define EGUITAR _T("pic/music/electric_guitar.png")
#define EUPHONIUM _T("pic/music/euphonium.png")
#define FLUTE _T("pic/music/flute.png") // Creative Commons
#define GUITAR _T("pic/music/guitar.png")
#define HARP _T("pic/music/harp.png")
#define IPU _T("pic/music/ipu.png")
#define JUG _T("pic/music/jug.png")
#define KAZOO _T("pic/music/kazoo.png")
#define LUTE _T("pic/music/lute.png")
#define MARACAS _T("pic/music/maracas.png")
#define NEY _T("pic/music/ney.png")
#define OBOE _T("pic/music/oboe.png")
#define PIANO _T("pic/music/piano.png")
#define QUENA _T("pic/music/quena.png")
#define RECORDER _T("pic/music/recorder.png")
#define SAX _T("pic/music/sax.png")
#define TRUMPET _T("pic/music/trumpet.png")
#define UKULELE _T("pic/music/ukulele.png")
#define VIOLIN _T("pic/music/violin.png")
#define WHISTLE _T("pic/music/whistle.png")
#define XUN _T("pic/music/xun.png")
#define XYLOPHONE _T("pic/music/xylophone.png")
#define YANGQIN _T("pic/music/yangqin.png") // ???
#define ZURNA _T("pic/music/zurna.png")

// Toys
#define ANKLET _T("pic/toys/anklet.png")
#define BALLOONS _T("pic/toys/balloons.png")
#define BICYCLE _T("pic/toys/bicycle.png")
#define CHALKBOARD _T("pic/toys/chalkboard.png")
#define DOLL _T("pic/toys/doll.png")
#define EASEL _T("pic/toys/easel.png")
#define FOOTBALL _T("pic/toys/football.png")
#define GLOVE _T("pic/toys/glove.png")
#define HORN _T("pic/toys/horn.png")
#define ICE_SKATE _T("pic/toys/ice_skate.png")
#define JUMP_ROPE _T("pic/toys/jump_rope.png")
#define KITE _T("pic/toys/kite.png")
#define LUNCHBOX _T("pic/toys/lunchbox.png")
#define MAGNET _T("pic/toys/magnet.png")
#define NECKLACE _T("pic/toys/necklace.png")
#define ORIGAMI _T("pic/toys/origami.png")
#define PAINT _T("pic/toys/paint.png")
#define PAPER_PLANE _T("pic/toys/paper_airplane.png")
#define QUILT _T("pic/toys/quilt.png")
#define ROCK_HORSE _T("pic/toys/rocking_horse.png")
#define SEESAW _T("pic/toys/seesaw.png")
#define TOP _T("pic/toys/top.png")
#define UNICYCLE _T("pic/toys/unicycle.png") // GNU Free Documentation License
#define VOLLEYBALL _T("pic/toys/volleyball.png")
#define WAGON _T("pic/toys/wagon.png")
//#define X
#define YOYO _T("pic/toys/yoyo.png")
#define ZIPLINE _T("pic/toys/zipline.png")

// Misc
#define AIRPLANE _T("pic/misc/airplane.png")
#define CLOCK _T("pic/misc/clock.png")
#define EARTH _T("pic/misc/earth.png")
#define FIRE _T("pic/misc/fire.png")
#define HAT _T("pic/misc/hat.png")
#define IGLOO _T("pic/misc/igloo.png")
#define JAR _T("pic/misc/jar.png")
#define KEYBOARD _T("pic/misc/keyboard.png")
#define NEWS _T("pic/misc/newspaper.png")
#define UMBRELLA _T("pic/misc/umbrella.png")
#define MAG_GLASS _T("pic/misc/mag_glass.png")
#define QUARTER _T("pic/misc/quarter.png")
#define STAR _T("pic/misc/star.png")
#define TRAIN _T("pic/misc/train.png")
#define VASE _T("pic/misc/vase.png")
#define WATCH _T("pic/misc/watch.png")
#define X_RAY _T("pic/misc/x_ray.png")
#define YINYANG _T("pic/misc/yinyang.png")
#define ZIPPER _T("pic/misc/zipper.png")

// Sounds
#define CHEER _T("sound/cheering.wav")

#define A _T("sound/alpha/A.wav")
#define B _T("sound/alpha/B.wav")
#define C _T("sound/alpha/C.wav")
#define D _T("sound/alpha/D.wav")
#define E _T("sound/alpha/E.wav")
#define F _T("sound/alpha/F.wav")
#define G _T("sound/alpha/G.wav")
#define H _T("sound/alpha/H.wav")
#define I _T("sound/alpha/I.wav")
#define J _T("sound/alpha/J.wav")
#define K _T("sound/alpha/K.wav")
#define L _T("sound/alpha/L.wav")
#define M _T("sound/alpha/M.wav")
#define N _T("sound/alpha/N.wav")
#define O _T("sound/alpha/O.wav")
#define P _T("sound/alpha/P.wav")
#define Q _T("sound/alpha/Q.wav")
#define R _T("sound/alpha/R.wav")
#define S _T("sound/alpha/S.wav")
#define T _T("sound/alpha/T.wav")
#define U _T("sound/alpha/U.wav")
#define V _T("sound/alpha/V.wav")
#define W _T("sound/alpha/W.wav")
#define X _T("sound/alpha/X.wav")
#define Y _T("sound/alpha/Y.wav")
#define Z _T("sound/alpha/Z.wav")
