
name: Build Tests

on:
  # push:
    # branches: [ master ]
    # paths:
      # - 'include/**.h'
      # - 'src/**.cpp'
      # - 'CMakeLists.txt'
      # - 'cmake/**.cmake'
  # pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # version 3.1 not available in default Ubuntu repos
      - name: Add wx 3.1 repo
        run: |
          sudo add-apt-repository ppa:leamas-alec/wxwidgets
          sudo apt update

      - name: Setup build environment
        run: |
          sudo apt install \
            g++ cmake \
            libwxgtk3.1-gtk3-dev \
            libsdl2-mixer-dev \
            ffmpeg

      - name: Test build
        run: |
          mkdir build && cd build
          cmake ../
          cmake --build ./
